"""remove AI modal

Revision ID: 0307314d1439
Revises: 202605110001
Create Date: 2026-05-14 20:43:08.496642

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0307314d1439'
down_revision: Union[str, None] = '202605110001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_interactions_prompt_hash'), table_name='ai_interactions')
    op.drop_index(op.f('ix_ai_interactions_provider'), table_name='ai_interactions')
    op.drop_index(op.f('ix_ai_interactions_status'), table_name='ai_interactions')
    op.drop_index(op.f('ix_ai_interactions_task_type'), table_name='ai_interactions')
    op.drop_index(op.f('ix_ai_interactions_trace_id'), table_name='ai_interactions')
    op.drop_table('ai_interactions')
    op.alter_column('audit_logs', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_constraint(op.f('patients_medical_record_number_key'), 'patients', type_='unique')
    op.drop_index(op.f('ix_patients_medical_record_number'), table_name='patients')
    op.create_index(op.f('ix_patients_medical_record_number'), 'patients', ['medical_record_number'], unique=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_patients_medical_record_number'), table_name='patients')
    op.create_index(op.f('ix_patients_medical_record_number'), 'patients', ['medical_record_number'], unique=False)
    op.create_unique_constraint(op.f('patients_medical_record_number_key'), 'patients', ['medical_record_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('audit_logs', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_table('ai_interactions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('trace_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('task_type', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('prompt_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_interactions_pkey'))
    )
    op.create_index(op.f('ix_ai_interactions_trace_id'), 'ai_interactions', ['trace_id'], unique=False)
    op.create_index(op.f('ix_ai_interactions_task_type'), 'ai_interactions', ['task_type'], unique=False)
    op.create_index(op.f('ix_ai_interactions_status'), 'ai_interactions', ['status'], unique=False)
    op.create_index(op.f('ix_ai_interactions_provider'), 'ai_interactions', ['provider'], unique=False)
    op.create_index(op.f('ix_ai_interactions_prompt_hash'), 'ai_interactions', ['prompt_hash'], unique=False)
    # ### end Alembic commands ###
