"""Adding new columns in users table

Revision ID: 7f49516727ef
Revises: 202605180002
Create Date: 2026-05-21 20:34:28.658422

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f49516727ef'
down_revision: Union[str, None] = '202605180002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('middle_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('sex_at_birth', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('required_relogin', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('token_version', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('sds_user_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sds_user_id')
    op.drop_column('users', 'token_version')
    op.drop_column('users', 'required_relogin')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'sex_at_birth')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'middle_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
