"""expand_practices_table

Revision ID: ce1b9a583c5a
Revises: e763acd5d472
Create Date: 2026-05-21 21:00:24.466108

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce1b9a583c5a'
down_revision: Union[str, None] = 'e763acd5d472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('practices', sa.Column('ods_code', sa.String(length=20), nullable=False, server_default=''))
    op.add_column('practices', sa.Column('notice', sa.String(length=255), nullable=True))
    op.add_column('practices', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('practices', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('practices', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('practices', sa.Column('practice_hours', sa.JSON(), nullable=True))
    op.add_column('practices', sa.Column('is_emis_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    # remove server defaults so new rows must supply values
    op.alter_column('practices', 'ods_code', server_default=None)
    op.alter_column('practices', 'is_emis_enabled', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practices', 'is_emis_enabled')
    op.drop_column('practices', 'practice_hours')
    op.drop_column('practices', 'email')
    op.drop_column('practices', 'website')
    op.drop_column('practices', 'phone')
    op.drop_column('practices', 'notice')
    op.drop_column('practices', 'ods_code')
    # ### end Alembic commands ###
